name: Laravel Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    types: [opened, synchronize, reopened]
    branches: [ "main" ]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, bcmath, sqlite, intl, pdo_sqlite, gd
          coverage: none

      - name: Install Composer Dependencies
        working-directory: ./tracker-app
        run: composer install --no-interaction --prefer-dist --no-progress
      
      - name: Set up test environment
        working-directory: ./tracker-app
        run: |
          cp .env.test .env
          php artisan key:generate
          php artisan config:clear
          php artisan cache:clear

      - name: Run Tests
        working-directory: ./tracker-app
        env:
          DB_CONNECTION: sqlite
          DB_DATABASE: ":memory:"
        run: php artisan test

