name: Code Style (PR)

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches: [ "main" ]

jobs:
  pint-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          coverage: none

      - name: Install Composer dependencies
        working-directory: ./tracker-app
        run: |
          composer install --no-interaction --no-progress
          composer dump-autoload 

      - name: Run Pint in test mode
        working-directory: ./tracker-app
        run: |
          ./vendor/bin/pint app/helpers.php --test
          ./vendor/bin/pint app/Bus --test
          ./vendor/bin/pint app/Contracts --test
          ./vendor/bin/pint app/Enums --test
          ./vendor/bin/pint app/Facades --test
          ./vendor/bin/pint app/Features --test
          ./vendor/bin/pint app/Http --test 
          ./vendor/bin/pint app/Jobs --test
          ./vendor/bin/pint app/Mail --test
          ./vendor/bin/pint app/Policies --test
          ./vendor/bin/pint app/Providers --test
          ./vendor/bin/pint app/Rules --test
          ./vendor/bin/pint app/Services --test
