name: Tests

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches: [ "main" ]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          extensions: mbstring, bcmath, sqlite, intl, pdo_sqlite, gd
          coverage: none

      - name: Cache Composer dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.composer/cache
            vendor
          key: ${{ runner.os }}-composer-${{ hashFiles('tracker-app/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-

      - name: Install Composer Dependencies
        working-directory: ./tracker-app
        run: composer install --no-interaction --prefer-dist --no-progress

      - name: Run Tests
        working-directory: ./tracker-app
        env:
          APP_KEY: ${{ secrets.TT_APP_KEY }}
        run: |
          # Run the test suite
          php artisan test 
